import type { APIRoute } from 'astro';
import { SEO_CONFIG } from '@/lib/seo-config';
import { serviceCategories, suratAreas, getAllBlogPosts, packages } from '@/lib/ffc-config';

export const prerender = true;

// Mirrors the route set the old Next.js app/sitemap.ts produced by scanning
// app/ for page.tsx folders (skipping dynamic [slug] segments): the fixed
// top-level pages, plus every service/area/keyword slug that used to be its
// own static folder and is now generated by src/pages/[slug].astro.
function getAllRoutes(): string[] {
  const fixedRoutes = [
    '/',
    '/about',
    '/contact',
    '/menu',
    '/virtual-tour',
    '/rooftop-experience',
    '/services',
    '/areas',
    '/packages',
    '/blog',
    '/privacy-policy',
    '/terms-conditions',
  ];

  const serviceRoutes = serviceCategories.map((service) => `/${service.slug}`);
  const keywordRoutes = serviceCategories.flatMap((service) =>
    service.keywords.map((keyword) => `/${keyword.slug}`),
  );
  const areaRoutes = suratAreas.map((area) => `/${area.slug}`);
  const packageRoutes = packages.map((pkg) => `/packages/${pkg.slug}`);
  const blogRoutes = getAllBlogPosts().map((post) => `/blog/${post.slug}`);

  return [...new Set([...fixedRoutes, ...serviceRoutes, ...keywordRoutes, ...areaRoutes, ...packageRoutes, ...blogRoutes])].sort();
}

function escapeXml(value: string): string {
  return value.replace(/&/g, '&amp;');
}

export const GET: APIRoute = () => {
  const baseUrl = SEO_CONFIG.siteUrl;
  const allRoutes = getAllRoutes();
  const lastModified = new Date().toISOString();

  const highPriorityPaths = new Set(['/']);
  const mediumPriorityKeywords = ['about', 'contact', 'services', 'service'];

  const urls = allRoutes.map((route) => {
    let priority = 0.7;
    let changefreq: 'daily' | 'weekly' | 'monthly' = 'weekly';

    if (highPriorityPaths.has(route)) {
      priority = 1.0;
      changefreq = 'daily';
    } else if (mediumPriorityKeywords.some((kw) => route.toLowerCase().includes(kw))) {
      priority = 0.9;
      changefreq = 'weekly';
    } else if (route.split('/').length <= 2) {
      priority = 0.8;
      changefreq = 'weekly';
    }

    return `  <url>
    <loc>${escapeXml(`${baseUrl}${route}`)}</loc>
    <lastmod>${lastModified}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority.toFixed(1)}</priority>
  </url>`;
  });

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>`;

  return new Response(xml, {
    headers: { 'Content-Type': 'application/xml' },
  });
};
